runtime: nodejs22

# Adicione estas linhas para garantir que uma instância esteja sempre ativa
# e para habilitar a afinidade de sessão.
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1

network:
  session_affinity: true

env_variables:
  DASHBOARD_PASSWORD: "d2o2i2s2"
  LOG_ENCRYPTION_KEY: "8f4e80d379f2e60fea5ac25e7c0d0d16e91785a6fc963e1eafaf2688a9c78f8b"