runtime: nodejs18

# Adicione estas linhas para garantir que uma instância esteja sempre ativa
# e para habilitar a afinidade de sessão.
instance_class: F1
automatic_scaling:
  min_instances: 1

network:
  session_affinity: true