# Define o ambiente como Node.js
runtime: nodejs20 # Ou nodejs18, etc., dependendo da sua versão

# Permite que o App Engine escale a aplicação, mantendo-a sempre online
instance_class: F1

# Configuração de escalonamento automático, coberta pelo nível gratuito
automatic_scaling:
  min_instances: 1
  max_instances: 2